// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPYOzOqnvPBeolYtFIPQ1UCDwYAbI3T0',
    appId: '1:1006775741778:ios:2abee6a1f382f58e741e8b',
    messagingSenderId: '1006775741778',
    projectId: 'ios-maps-zia',
    storageBucket: 'ios-maps-zia.appspot.com',
    iosClientId: '1006775741778-o1a2pk6t60pcgpd1oam6i2le3ohpegvj.apps.googleusercontent.com',
    iosBundleId: 'com.pzapps.gpsmapsnavigation',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpXCWWpHLhBs8ZSOvIpwnLdf56JB7v8Q',
    appId: '1:251272898728:android:e581b2252111c9ae653a9d',
    messagingSenderId: '251272898728',
    projectId: 'gps-naviation-ghalbail',
    storageBucket: 'gps-naviation-ghalbail.appspot.com',
  );
}
